

services:
  real-estate-database:
    container_name: real-estate-database
    image: postgres:17.5-alpine3.22
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'real-estate-db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

